mcfields/newsletter/urls.py
from django.urls import path
from mcfields.newsletter import views


app_name = 'newsletter'
urlpatterns = [
    path('', views.indice_newsletters, name='indice_newsletters'),
    path('<slug:subject_slug>/<slug:slug>', views.detalhe_newsletter, name='detalhe_newsletter'),
    path('adm/post/', views.post_newsletter, name='post'),
    path('adm/edicao/<int:id>/', views.edicao_newsletter, name='edicao'),
    path('adm/remocao/<int:id>/', views.remocao_newsletter, name='remocao'),
]

mcfields/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcfields.base.urls')),
    path('newsletter/', include('mcfields.newsletter.urls')),
    path('servicos/', include('mcfields.servicos.urls')),
    path('videos/', include('mcfields.videos.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Configurações django-debug-toolbar
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

mcfields/newsletter/models.py
from django.db import models
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from ordered_model.models import OrderedModel

from mcfields.base.models import Subject


class Newsletter(OrderedModel):
    title = models.CharField(max_length=64, verbose_name='Título')
    intro = models.TextField(max_length=512, verbose_name='Introdução')
    content = CKEditor5Field(verbose_name='Conteúdo')
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='Assunto')
    pub_date = models.DateField(auto_now_add=True, verbose_name='Data de publicação')
    edit_date = models.DateField(auto_now=True, verbose_name='Data de edição')
    author = models.CharField(max_length=32, verbose_name='Autor')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('newsletter:detalhe_newsletter',
                       kwargs={'subject_slug': self.subject.slug, 'slug': self.slug})

    def get_edition_url(self):
        return reverse('newsletter:edicao', args=(self.pk,))

    def get_removal_url(self):
        return reverse('newsletter:remocao', args=(self.pk,))

mcfields/newsletter/forms.py
from django.forms import ModelForm
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from mcfields.newsletter.models import Newsletter


class NewsletterForm(ModelForm):
    criar_rascunho = forms.ChoiceField(
        choices=(('YES', 'Sim'), ('NO', 'Não')),
        widget=forms.RadioSelect,
        label='Criar rascunho de email:')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].required = False

    class Meta:
        model = Newsletter
        fields = '__all__'
        widgets = {
            'content': CKEditor5Widget(attrs={'class': 'django_ckeditor_5'})
        }

mcfields/newsletter/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render
from mcfields import settings
from mcfields.newsletter import facade
from mcfields.newsletter.forms import NewsletterForm
from mcfields.newsletter.models import Newsletter


def indice_newsletters(request):
    newsletters = facade.listar_newsletters_ordenadas()
    return render(request, 'newsletter/indice_newsletter.html', {'newsletters': newsletters})


def detalhe_newsletter(request, slug, subject_slug):
    newsletter = Newsletter.objects.select_related('subject').get(slug=slug)
    return render(request, 'newsletter/detalhe_newsletter.html', {'newsletter': newsletter})


@login_required
@permission_required('newsletter.add_newsletter', login_url='/nao_permitido/')
def post_newsletter(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            path = request.path
            api_key = settings.SENDGRID_API_KEY
            titulo = request.POST['title']
            sg_list_id = settings.SENDGRID_LIST_ID
            sg_news_design_id = settings.SENDGRID_NEWSLETTER_DESIGN_ID
            if request.POST['criar_rascunho'] == 'YES':
                facade.criar_rascunho(key=api_key, titulo=titulo, list_id=sg_list_id, design_id=sg_news_design_id)
            return render(request, 'base/post_success.html',
                          {'titulo': request.POST['title'], 'path': path})
        else:
            return render(request, 'newsletter/post_newsletter.html', {'form': form})
    form = NewsletterForm()
    return render(request, 'newsletter/post_newsletter.html', {'form': form})


@login_required
@permission_required('newsletter.change_newsletter', login_url='/nao_permitido/')
def edicao_newsletter(request, id):
    newsletter = Newsletter.objects.get(id=id)
    if request.POST:
        form = NewsletterForm(request.POST, instance=newsletter)
        if form.is_valid():
            form.save()
            api_key = settings.SENDGRID_API_KEY
            titulo = request.POST['title']
            sg_list_id = settings.SENDGRID_LIST_ID
            sg_news_design_id = settings.SENDGRID_NEWSLETTER_DESIGN_ID
            if request.POST['criar_rascunho'] == 'YES':
                facade.criar_rascunho(key=api_key, titulo=titulo, list_id=sg_list_id, design_id=sg_news_design_id)
            return render(request, 'base/edicao_concluida.html',
                          {'newsletter': newsletter})
        else:
            return render(request, 'newsletter/post_newsletter.html',
                          {'form': form, 'newsletter': newsletter})
    form = NewsletterForm(instance=newsletter)
    return render(request, 'newsletter/post_newsletter.html',
                  {'form': form, 'newsletter': newsletter})


@login_required
@permission_required('newsletter.delete_newsletter', login_url='/nao_permitido/')
def remocao_newsletter(request, id):
    newsletter = Newsletter.objects.get(id=id)
    if request.method == 'POST':
        titulo = newsletter.title
        newsletter.delete()
        path = request.path
        return render(request, 'base/remocao_concluida.html', {'titulo': titulo, 'path': path})
    return render(request, 'newsletter/confirmacao_remocao.html', {'newsletter': newsletter})

mcfields/newsletter/templates/newsletter/confirmacao_remocao.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/confirmacao_remocao.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Confirmar remoção</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-news_removal">
        <h4 class="removal-msg">Tem certeza que deseja remover a newsletter "<strong>{{ newsletter.title }}</strong>"?</h4>
        <form action="{% url 'newsletter:remocao' newsletter.id %}" method="POST">
            {% csrf_token %}
            <a class="canc-removal-button" href="{{ newsletter.get_absolute_url }}">Cancelar</a>
            <button class="conf-removal-button" type="submit">Confirmar</button>
        </form>
    </div>
{% endblock maincontent_2 %}

mcfields/newsletter/templates/newsletter/detalhe_newsletter.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'newsletter/css/detalhe_newsletter.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/pag_detalhes.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - {{ newsletter.title }}</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-newsletter-det">
        {% if perms.newsletter.change_newsletter %}
            <a class="update-link" href="{{ newsletter.get_edition_url }}">Editar</a>
        {% endif %}
        {% if perms.newsletter.delete_newsletter %}
            <a class="removal-link" href="{{ newsletter.get_removal_url }}">Remover</a>
        {% endif %}
        <h1 class="title">{{ newsletter.title }}</h1>
        <h5 id="newsletter-intro">{{ newsletter.intro|linebreaks }}</h5>
        <div id="newsletter-subject">{{ newsletter.subject }}</div>
        <div id="news-adit-info">
            <div id="newsletter-author">{{ newsletter.author }}</div>
            <div id="news-pub-date">{{ newsletter.pub_date|date:"d/m/Y" }}</div>
        </div>
        <hr id="hr-main-content">
        <div id="newsletter-content">{{ newsletter.content|safe|linebreaks }}</div>
    </div>
{% endblock maincontent_2 %}

mcfields/newsletter/templates/newsletter/indice_newsletter.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'newsletter/css/indice_newsletter.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Newsletter</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-newsletter">
        <h1>Newsletter</h1>
        {% if perms.newsletter.add_newsletter %}
            <a id="new-pub-link" href="{% url 'newsletter:post' %}">Nova publicação</a>
        {% endif %}
        {% for newsletter in newsletters %}
            <a href="{{ newsletter.get_absolute_url }}" class="newsletter-box-link">
                <div class="newsletter-box">
                    <h4 class="newsletter-title">{{ newsletter.title }}</h4>
                    <p class="newsletter-comment">{{ newsletter.intro }}</p>
                    <div class="adit-info-newsletter">
                        <div class="newsletter-author">{{ newsletter.author }}</div>
                        <div class="newsletter-date">{{ newsletter.pub_date|date:"d/m/Y" }}</div>
                    </div>
                </div>
            </a>
        {% empty %}
            <p>Não há newsletters cadastradas.</p>
        {% endfor %}
    </div>
{% endblock maincontent_2 %}

mcfields/newsletter/templates/newsletter/nao_permitido_newsletter.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'newsletter/css/nao_permitido_news.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Acesso não permitido</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-not-allowed-news">
        <h4 id="not_allowed-msg">Desculpe, {{ user.first_name }}, mas você não tem acesso à este conteúdo.</h4>
    </div>
{% endblock maincontent_2 %}

mcfields/newsletter/templates/newsletter/newsletter_editada.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'newsletter/css/newsletter_editada.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Edição concluída</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-update-sucess">
        <h4 id="success-update-msg">A newsletter "<strong>{{ titulo }}</strong>" foi editada com sucesso.</h4>
    </div>
{% endblock maincontent_2 %}

mcfields/newsletter/templates/newsletter/post_newsletter.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/formularios.css' %}">
{% endblock css %}

{% block title %}
    {% if newsletter.id %}
        <title>McField's - Edição de Newsletter</title>
    {% else %}
        <title>McField's - Nova Newsletter</title>
    {% endif %}
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-post-newsletter">
        {% if newsletter.id %}
            <h1 class="form-title">Edição da Newsletter "{{ newsletter.title }}"</h1>
        {% else %}
            <h1 class="form-title">Nova Newsletter</h1>
        {% endif %}
        <form action="" method="POST" class="disp-flex flex-dir-col">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }} {{ field }}
                    <p class="errornote">{{ field.errors }}</p>
                </div>
            {{ field.help_text }}
            {% endfor %}
            <div class="form-buttons">
                {% if newsletter %}
                    <a class="canc-button" href="{{ newsletter.get_absolute_url }}">Cancelar</a>
                {% else %}
                    <a class="canc-button" href="{% url 'newsletter:indice_newsletters' %}">Cancelar</a>
                {% endif %}
                <button class="submit-button" type="submit">Publicar</button>
            </div>
        </form>
    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'newsletter/js/post_newsletter.js' %}" ></script>
{% endblock scripts %}

mcfields/newsletter/templates/newsletter/remocao_concluida.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'newsletter/css/remocao_concluida.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Remoção concluída</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-success-removal">
        <h4 id="success-removal-msg">A newsletter "<strong>{{ titulo }}</strong>" foi removida com sucesso.</h4>
    </div>
{% endblock maincontent_2 %}