mcfields/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcfields.base.urls')),
    path('newsletter/', include('mcfields.newsletter.urls')),
    path('servicos/', include('mcfields.servicos.urls')),
    path('videos/', include('mcfields.videos.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Configurações django-debug-toolbar
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

mcfields/videos/urls.py
from django.urls import path
from mcfields.videos import views

app_name = 'videos'
urlpatterns = [
    path('', views.indice_videos, name='indice'),
    path('adm/post', views.post_video, name='post'),
    path('adm/edicao/<int:id>', views.edicao_video, name='edicao'),
    path('adm/remocao/<int:id>', views.remocao_video, name='remocao'),
    path('<slug:subject_slug>/<slug:slug>', views.detalhe_video, name='detalhe_video'),
]

mcfields/videos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel
from mcfields.base.models import Subject


class Video(OrderedModel):
    title = models.CharField(max_length=64, verbose_name='Título')
    description = models.TextField(verbose_name='Descrição')
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='Assunto')
    platform_id = models.CharField(max_length=48, verbose_name='ID da plataforma')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Slug')
    post_date = models.DateField(auto_now_add=True, verbose_name='Data de postagem')
    edit_date = models.DateField(auto_now=True, verbose_name='Data de postagem')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('videos:detalhe_video', kwargs={'slug': self.slug, 'subject_slug': self.subject.slug})

    def get_edition_url(self):
        return reverse('videos:edicao', args=(self.pk,))

    def get_removal_url(self):
        return reverse('videos:remocao', args=(self.pk,))

mcfields/videos/forms.py
from django.forms import ModelForm
from django import forms
from mcfields.videos.models import Video


class VideoForm(ModelForm):
    criar_rascunho = forms.ChoiceField(
        choices=(('YES', 'Sim'), ('NO', 'Não')),
        widget=forms.RadioSelect,
        label='Criar rascunho de email:')

    class Meta:
        model = Video
        fields = '__all__'

mcfields/videos/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render

from mcfields import settings
from mcfields.videos import facade
from mcfields.videos.forms import VideoForm
from mcfields.videos.models import Video


def indice_videos(request):
    assuntos = facade.listar_assuntos_com_videos()
    return render(request, 'videos/indice_videos.html', {'assuntos': assuntos})


def detalhe_video(request, slug, subject_slug):
    video = Video.objects.select_related('subject').get(slug=slug)
    return render(request, 'videos/detalhe_video.html', {'video': video})


@login_required
@permission_required('videos.add_video', login_url='/nao_permitido/')
def post_video(request):
    if request.POST:
        form = VideoForm(request.POST)
        if form.is_valid():
            form.save()
            path = request.path
            api_key = settings.SENDGRID_API_KEY
            titulo = request.POST['title']
            sg_list_id = settings.SENDGRID_LIST_ID
            sg_video_design_id = settings.SENDGRID_VIDEO_DESIGN_ID
            if request.POST['criar_rascunho'] == 'YES':
                facade.criar_rascunho(key=api_key, titulo=titulo, list_id=sg_list_id, design_id=sg_video_design_id)
            return render(request, 'base/post_success.html',
                          {'titulo': request.POST['title'], 'path': path})
        else:
            return render(request, 'videos/novo_video.html', {'form': form})
    form = VideoForm()
    return render(request, 'videos/novo_video.html', {'form': form})


@login_required
@permission_required('videos.change_video', login_url='/nao_permitido/')
def edicao_video(request, id):
    video = Video.objects.get(id=id)
    if request.method == 'POST':
        form = VideoForm(request.POST, instance=video)
        if form.is_valid():
            form.save()
            api_key = settings.SENDGRID_API_KEY
            titulo = request.POST['title']
            sg_list_id = settings.SENDGRID_LIST_ID
            sg_video_design_id = settings.SENDGRID_VIDEO_DESIGN_ID
            if request.POST['criar_rascunho'] == 'YES':
                facade.criar_rascunho(key=api_key, titulo=titulo, list_id=sg_list_id, design_id=sg_video_design_id)
            return render(request, 'base/edicao_concluida.html', {'video': video})
        else:
            return render(request, 'videos/novo_video.html', {'form': form, 'video': video})
    form = VideoForm(instance=video)
    return render(request, 'videos/novo_video.html', {'form': form, 'video': video})


@login_required
@permission_required('videos.delete_video', login_url='/nao_permitido/')
def remocao_video(request, id):
    video = Video.objects.get(id=id)
    if request.method == 'POST':
        titulo = video.title
        video.delete()
        path = request.path
        return render(request, 'base/remocao_concluida.html', {'titulo': titulo, 'path': path})
    return render(request, 'videos/confirmacao_remocao.html', {'video': video})

mcfields/videos/templates/videos/confirmacao_remocao.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/confirmacao_remocao.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Confirmar remoção</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-video_removal">
        <h4 class="removal-msg">Tem certeza que deseja remover o vídeo "<strong>{{ video.title }}</strong>"?</h4>
        <form action="{% url 'videos:remocao' video.id %}" method="POST">
            {% csrf_token %}
            <a class="canc-removal-button" href="{% url 'videos:detalhe_video' subject_slug=video.subject.slug slug=video.slug %}">Cancelar</a>
            <button class="conf-removal-button" type="submit">Confirmar</button>
        </form>
    </div>
{% endblock maincontent_2 %}

mcfields/videos/templates/videos/detalhe_video.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'videos/css/detalhe_video.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/pag_detalhes.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - {{ video.title }}</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-video-det">
        {% if perms.videos.change_video %}
            <a class="update-link" href="{{ video.get_edition_url }}">Editar</a>
        {% endif %}
        {% if perms.videos.delete_video %}
            <a class="removal-link" href="{{ video.get_removal_url }}">Remover</a>
        {% endif %}
        <iframe src="https://www.youtube.com/embed/{{ video.platform_id }}?rel=0"
                title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write;
                encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        <h4 id="video-title">{{ video.title }}</h4>
        <p id="video-subject">{{ video.subject }}</p>
        <div id="video-description">
            <h6 id="video-post-date">{{ video.post_date }}</h6>
            <p>{{ video.description|linebreaks }}</p>
        </div>
    </div>
{% endblock maincontent_2 %}

mcfields/videos/templates/videos/indice_videos.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'videos/css/indice_videos.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Vídeos</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-videos">
        <h1>Vídeos</h1>
        {% if perms.videos.add_video %}
            <a id="video-pub-link" href="{% url 'videos:post' %}">Novo vídeo</a>
        {% endif %}
        {% for assunto in assuntos %}
            <div class="subject-div">
                <div class="cover unclicked"></div>
                <div class="subject-div-text">
                    <h4>{{ assunto.title }}</h4>
                    <p class="subject-description">{{ assunto.description }}</p>
                </div>
                <i class="bi bi-caret-down-fill light-green"></i>
            </div>
            <ol class="videos-list hidden-videos">
                {% for video in assunto.videos %}
                    <li class="video-list-item">
                        <a class="video-link" href="{{ video.get_absolute_url }}">
                            <div>
                                <div>{{ video.title }}</div>
                                <div class="post-date">{{ video.post_date|date:"d/m/Y" }}</div>
                            </div>
                            <i class="bi bi-play-circle"></i>
                        </a>
                    </li>
                {% empty %}
                    <li>Não há vídeos cadastrados.</li>
                {% endfor %}
            </ol>
        {% empty %}
            <p>Não há vídeos cadastrados.</p>
        {% endfor %}
    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'videos/js/indice_videos.js' %}"></script>
{% endblock scripts %}

mcfields/videos/templates/videos/novo_video.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/formularios.css' %}">
{% endblock css %}

{% block title %}
    {% if video %}
        <title>McField's - Edição de vídeo</title>
    {% else %}
        <title>McField's - Novo Vídeo</title>
    {% endif %}
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-post-video">
        {% if video %}
            <h1 class="form-title">Edição do Vídeo "{{ video.title }}"</h1>
        {% else %}
            <h1 class="form-title">Novo Vídeo</h1>
        {% endif %}
        <form class="disp-flex flex-dir-col" action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }} {{ field }}
                    <p class="errornote">{{ field.errors }}</p>
                </div>
                {{ field.help_text }}
            {% endfor %}
            <div class="form-buttons">
                <a class="canc-button" href="{% url 'videos:indice' %}">Cancelar</a>
                <button class="submit-button" type="submit">Publicar</button>
            </div>
        </form>
    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'videos/js/novo_video.js' %}" ></script>
{% endblock scripts %}