mcfields/base/urls.py
from django.urls import path
from mcfields.base import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('politica_privacidade', views.politica_privac, name='politica_privacidade'),
    path('contato', views.contato, name='contato'),
    path('indice_mensagens', views.indice_mensagens, name='indice_mensagens'),
    path('mensagem/<int:id>', views.detalhe_mensagem, name='detalhe_mensagem'),
    path('mensagem/adm/remocao/<int:id>', views.remoc_contact, name='remoc_contact'),
    path('sobre', views.sobre, name='sobre'),
    path('assuntos', views.subjects, name='subjects'),
    path('assuntos/adm/adicao', views.adic_subject, name='adic_subject'),
    path('assuntos/adm/edicao/<int:id>', views.edic_subject, name='edic_subject'),
    path('assuntos/adm/remocao/<int:id>', views.remoc_subject, name='remoc_subject'),
    path('inscricao_concluida', views.inscricao_email, name='inscricao_email'),
    path('accounts/login/', views.UserLogin.as_view(), name='login'),
    path('nao_permitido/', views.nao_permitido, name='nao_permitido'),
]

mcfields/servicos/urls.py
from django.urls import path
from mcfields.servicos import views

app_name = 'servicos'
urlpatterns = [
    path('<slug:slug>', views.detalhe_servico, name='detalhe_servico'),
    path('adm/adic', views.adicionar_servico, name='adicionar'),
    path('adm/edicao/<int:id>', views.editar_servico, name='edicao'),
    path('adm/remocao/<int:id>', views.remocao_servico, name='remocao'),
]

mcfields/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcfields.base.urls')),
    path('newsletter/', include('mcfields.newsletter.urls')),
    path('servicos/', include('mcfields.servicos.urls')),
    path('videos/', include('mcfields.videos.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Configurações django-debug-toolbar
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

mcfields/servicos/models.py
from django.db import models
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from ordered_model.models import OrderedModel


class Service(OrderedModel):
    title = models.CharField(max_length=64, verbose_name='Título')
    intro = models.TextField(max_length=512, verbose_name='Introdução')
    home_picture = models.ImageField(verbose_name='Foto da home page', upload_to='service_photos')
    content = CKEditor5Field(verbose_name='Conteúdo')
    slug = models.SlugField(max_length=64, verbose_name='Slug', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('servicos:detalhe_servico', args=(self.slug,))

    def get_edition_url(self):
        return reverse('servicos:edicao', args=(self.pk,))

    def get_removal_url(self):
        return reverse('servicos:remocao', args=(self.pk,))

mcfields/servicos/forms.py
from django.forms import ModelForm
from django_ckeditor_5.widgets import CKEditor5Widget
from mcfields.servicos.models import Service


class ServiceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].required = False

    class Meta:
        model = Service
        fields = '__all__'
        widgets = {
            'content': CKEditor5Widget(attrs={'class': 'django_ckeditor_5'})
        }

mcfields/servicos/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render

from mcfields.servicos.forms import ServiceForm
from mcfields.servicos.models import Service


def detalhe_servico(request, slug):
    service = Service.objects.get(slug=slug)
    return render(request, 'servicos/detalhe_servico.html', {'servico': service})


@login_required
@permission_required('servicos.add_service', login_url='/nao_permitido/')
def adicionar_servico(request):
    if request.POST:
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            path = request.path
            return render(request, 'base/post_success.html',
                          {'titulo': request.POST['title'], 'path': path})
        else:
            return render(request, 'servicos/adicao_servico.html', {'form': form})
    form = ServiceForm()
    return render(request, 'servicos/adicao_servico.html', {'form': form})


@login_required
@permission_required('servicos.change_service', login_url='/nao_permitido/')
def editar_servico(request, id):
    service = Service.objects.get(id=id)
    if request.POST:
        form = ServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()
            return render(request, 'base/edicao_concluida.html', {'servico': service})
        else:
            return render(request, 'servicos/adicao_servico.html',
                          {'form': form, 'servico': service})
    form = ServiceForm(instance=service)
    return render(request, 'servicos/adicao_servico.html', {'form': form, 'servico': service})


@login_required
@permission_required('servicos.delete_service', login_url='/nao_permitido/')
def remocao_servico(request, id):
    service = Service.objects.get(id=id)
    if request.method == 'POST':
        titulo = service.title
        path = request.path
        service.delete()
        return render(request, 'base/remocao_concluida.html', {'titulo': titulo, 'path': path})
    return render(request, 'servicos/confirmacao_remocao.html', {'servico': service})

mcfields/servicos/templates/servicos/adicao_servico.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/formularios.css' %}">
{% endblock css %}

{% block title %}
    {% if servico %}
        <title>McField's - Edição de Serviço</title>
    {% else %}
        <title>McField's - Novo Serviço</title>
    {% endif %}
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-service-adit">
        {% if servico %}
            <h1 class="form-title">Edição do Serviço "{{ servico.title }}"</h1>
        {% else %}
            <h1 class="form-title">Novo Serviço</h1>
        {% endif %}
        <form class="disp-flex flex-dir-col" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }} {{ field }}
                    <p class="errornote">{{ field.errors }}</p>
                </div>
            {{ field.help_text }}
            {% endfor %}
            <div class="form-buttons">
                {% if servico %}
                    <a class="canc-button" href="{% url 'servicos:detalhe_servico' servico.slug %}">Cancelar</a>
                {% else %}
                    <a class="canc-button" href="{% url 'base:home' %}">Cancelar</a>
                {% endif %}
                <button class="submit-button" type="submit">Publicar</button>
            </div>
        </form>

    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'servicos/js/adicao_servico.js' %}" ></script>
{% endblock scripts %}

mcfields/servicos/templates/servicos/confirmacao_remocao.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/confirmacao_remocao.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Confirmar remoção</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-serv_removal">
        <h4 class="removal-msg">Tem certeza que deseja remover o serviço "<strong>{{ servico.title }}</strong>"?</h4>
        <form action="{% url 'servicos:remocao' servico.id %}" method="POST">
            {% csrf_token %}
            <a class="canc-removal-button" href="{% url 'servicos:detalhe_servico' servico.slug %}">Cancelar</a>
            <button class="conf-removal-button" type="submit">Confirmar</button>
        </form>
    </div>
{% endblock maincontent_2 %}

mcfields/servicos/templates/servicos/detalhe_servico.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'servicos/css/detalhe_servico.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/pag_detalhes.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - {{ servico.title }}</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-service-det">
        {% if perms.servicos.add_service %}
            <a id="service-adit-link" href="{% url 'servicos:adicionar' %}">Novo serviço</a>
        {% endif %}
        {% if perms.servicos.change_service %}
            <a class="update-link" href="{{ servico.get_edition_url }}">Editar</a>
        {% endif %}
        {% if perms.servicos.delete_service %}
            <a class="removal-link" href="{{ servico.get_removal_url }}">Remover</a>
        {% endif %}
        <h1 class="title">{{ servico.title }}</h1>
        <div id="service-content">{{ servico.content|safe|linebreaks }}</div>
    </div>
{% endblock maincontent_2 %}