mcfields/base/urls.py
from django.urls import path
from mcfields.base import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('politica_privacidade', views.politica_privac, name='politica_privacidade'),
    path('contato', views.contato, name='contato'),
    path('indice_mensagens', views.indice_mensagens, name='indice_mensagens'),
    path('mensagem/<int:id>', views.detalhe_mensagem, name='detalhe_mensagem'),
    path('mensagem/adm/remocao/<int:id>', views.remoc_contact, name='remoc_contact'),
    path('sobre', views.sobre, name='sobre'),
    path('assuntos', views.subjects, name='subjects'),
    path('assuntos/adm/adicao', views.adic_subject, name='adic_subject'),
    path('assuntos/adm/edicao/<int:id>', views.edic_subject, name='edic_subject'),
    path('assuntos/adm/remocao/<int:id>', views.remoc_subject, name='remoc_subject'),
    path('inscricao_concluida', views.inscricao_email, name='inscricao_email'),
    path('accounts/login/', views.UserLogin.as_view(), name='login'),
    path('nao_permitido/', views.nao_permitido, name='nao_permitido'),
]

mcfields/servicos/urls.py
from django.urls import path
from mcfields.servicos import views

app_name = 'servicos'
urlpatterns = [
    path('<slug:slug>', views.detalhe_servico, name='detalhe_servico'),
    path('adm/adic', views.adicionar_servico, name='adicionar'),
    path('adm/edicao/<int:id>', views.editar_servico, name='edicao'),
    path('adm/remocao/<int:id>', views.remocao_servico, name='remocao'),
]

mcfields/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcfields.base.urls')),
    path('newsletter/', include('mcfields.newsletter.urls')),
    path('servicos/', include('mcfields.servicos.urls')),
    path('videos/', include('mcfields.videos.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Configurações django-debug-toolbar
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

mcfields/base/models.py
from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db import models
from ordered_model.models import OrderedModel


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given, email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        # GlobalUserModel = apps.get_model(
        #     self.model._meta.app_label, self.model._meta.object_name
        # )
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, **extra_fields)

    def with_perm(
        self, perm, is_active=True, include_superusers=True, backend=None, obj=None
    ):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    "You have multiple authentication backends configured and "
                    "therefore must provide the `backend` argument."
                )
        elif not isinstance(backend, str):
            raise TypeError(
                "backend must be a dotted import path string (got %r)." % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, "with_perm"):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name.
        """
        full_name = "%s" % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Subject(OrderedModel):
    title = models.CharField(max_length=64, verbose_name='Título')
    description = models.TextField(max_length=256, verbose_name='Descrição')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Slug')

    def __str__(self):
        return self.title

    def get_edition_url(self):
        return reverse('base:edic_subject', args=(self.pk,))

    def get_removal_url(self):
        return reverse('base:remoc_subject', args=(self.pk,))


class Contact(OrderedModel):
    name = models.CharField(max_length=32, verbose_name='Nome')
    email = models.EmailField(max_length=48, verbose_name='Email')
    subject = models.CharField(max_length=128, verbose_name='Assunto')
    message = models.TextField(verbose_name='Mensagem')
    agree_with_policy = models.BooleanField()
    send_date = models.DateField(auto_now_add=True, verbose_name='Data de envio')

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('base:detalhe_mensagem', args=(self.pk,))

    def get_removal_url(self):
        return reverse('base:remoc_contact', args=(self.pk,))

mcfields/servicos/models.py
from django.db import models
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from ordered_model.models import OrderedModel


class Service(OrderedModel):
    title = models.CharField(max_length=64, verbose_name='Título')
    intro = models.TextField(max_length=512, verbose_name='Introdução')
    home_picture = models.ImageField(verbose_name='Foto da home page', upload_to='service_photos')
    content = CKEditor5Field(verbose_name='Conteúdo')
    slug = models.SlugField(max_length=64, verbose_name='Slug', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('servicos:detalhe_servico', args=(self.slug,))

    def get_edition_url(self):
        return reverse('servicos:edicao', args=(self.pk,))

    def get_removal_url(self):
        return reverse('servicos:remocao', args=(self.pk,))

mcfields/base/forms.py
from django import forms
from django.core.exceptions import ValidationError

from mcfields.base.models import Subject, Contact


class EmailForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=128,
                             widget=forms.EmailInput(attrs={'placeholder': 'example@gmail.com'}),
                             error_messages={'required': 'É necessário informar um email para cadastro.',
                                             'invalid': 'Informe um endereço de email válido.'})
    policy_agreement = forms.BooleanField(error_messages={
        'required': 'É necessário concordar com nossa política de privacidade.'})


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def clean_agree_with_policy(self):
        data = self.cleaned_data['agree_with_policy']
        if not data:
            raise ValidationError('Você deve concordar com nossa política de privacidade.')
        return data

mcfields/base/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse
from mcfields import settings
from mcfields.base.forms import EmailForm, SubjectForm, ContactForm
from mcfields.base import facade
from mcfields.base.models import Subject, Contact
from mcfields.servicos.models import Service


def home(request):
    services = Service.objects.all()
    return render(request, 'base/home.html', {'servicos': services})


def sobre(request):
    return render(request, 'base/sobre.html')


def inscricao_email(request):
    """
    Antes de inscrever um email é verificado se este está registrado no grupo de emails descadastrados.
    Caso esteja, o email será apenas removido do grupo e passará a receber emails novamente. Caso esteja
    no grupo de descadastrados não é necessário adicioná-lo à lista de emails, pois este já estará presente.
    :param request:
    :return:
    """
    if request.POST:
        emailform = EmailForm(request.POST)
        if emailform.is_valid():
            email = emailform.cleaned_data['email']
            api_key = settings.SENDGRID_API_KEY
            sg_list_id = settings.SENDGRID_LIST_ID
            suppr_group_id = settings.SUPPRESSION_GROUP_ID
            resp_email_desc = facade.checar_email_descadastrado(key=api_key, email=email, suppr_group_id=suppr_group_id)
            if bytes(email, 'utf-8') in resp_email_desc.body:
                facade.remover_da_lista_desc(key=api_key, email=email, supp_group_id=suppr_group_id)
            else:
                facade.cadastrar_email(key=api_key, user_email=email, list_id=sg_list_id)
            return render(request, 'base/inscricao_concluida.html', {'email': email})
        else:
            email_errors = emailform.errors.get('email')
            policy_agreement_errors = emailform.errors.get('policy_agreement')
            context = {'email_errors': email_errors, 'policy_agreement_errors': policy_agreement_errors}
            return render(request, 'base/inscricao_concluida.html', context=context)
    return redirect(reverse('base:home'))


@login_required
def nao_permitido(request):
    return render(request, 'base/nao_permitido.html')


class UserLogin(LoginView):
    template_name = 'registration/user_login.html'
    next_page = '/'


@login_required
@permission_required('base.add_subject', login_url='/nao_permitido/')
def adic_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            titulo = request.POST['title']
            path = request.path
            return render(request, 'base/post_success.html', {'titulo': titulo, 'path': path})
        else:
            return render(request, 'base/adic_subject.html', {'form': form})
    form = SubjectForm()
    return render(request, 'base/adic_subject.html', {'form': form})


@login_required
@permission_required('base.change_subject', login_url='/nao_permitido/')
def edic_subject(request, id):
    subject = Subject.objects.get(id=id)
    if request.method == 'POST':
        form = SubjectForm(request.POST, instance=subject)
        if form.is_valid():
            form.save()
            return render(request, 'base/edicao_concluida.html', {'subject': subject})
        else:
            return render(request, 'base/adic_subject.html', {'form': form, 'subject': subject})
    form = SubjectForm(instance=subject)
    return render(request, 'base/adic_subject.html', {'form': form, 'subject': subject})


@login_required
@permission_required('base.view_subject', login_url='/nao_permitido/')
def subjects(request):
    subs = facade.buscar_subjects_com_conteudos()
    return render(request, 'base/assuntos.html', {'subjects': subs})


@login_required
@permission_required('base.delete_subject', login_url='/nao_permitido/')
def remoc_subject(request, id):
    """
    Acessa a página de remoção e remove assuntos. A página de remoção só será acessada se o assunto a ser
    removido não possuir nenhum outro conteúdo relacionado, caso contrário o usuário será direcionado para
    a página de remoção não permitida.
    """
    sub = Subject.objects.get(id=id)
    titulo = sub.title
    if sub.video_set.exists() or sub.newsletter_set.exists():
        return render(request, 'base/remocao_nao_permitida.html', {'titulo': titulo})
    if request.method == 'POST':
        path = request.path
        sub.delete()
        return render(request, 'base/remocao_concluida.html', {'titulo': titulo, 'path': path})
    return render(request, 'base/conf_remoc_subject.html', {'subject': sub})


def politica_privac(request):
    return render(request, 'base/politica_privacidade.html')


def contato(request):
    """
    Acessa a página de contato. Após preenchido e submetido o formulário, uma mensagem de email será enviada
    do remetente configurado como FROM_EMAIL nas váriáveis de ambiente para o destinatário TO_EMAIL, também
    configurado nas variáveis de ambiente. A mensagem será enviada através da API do SendGrid via função
    enviar_mensagem().
    """
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            key = settings.SENDGRID_API_KEY
            name = request.POST['name']
            email = request.POST['email']
            subject = request.POST['subject']
            message = request.POST['message']
            from_email = settings.FROM_EMAIL
            to_email = settings.TO_EMAIL
            form.save()
            facade.enviar_mensagem(key=key, name=name, email=email, subject=subject, message=message,
                                   from_email=from_email, to_email=to_email)
            return render(request, 'base/envio_msg_concludo.html')
        else:
            return render(request, 'base/contato.html', {'form': form})
    form = ContactForm()
    return render(request, 'base/contato.html', {'form': form})


@login_required
@permission_required('base.view_contact', login_url='/nao_permitido/')
def indice_mensagens(request):
    mensagens = facade.listar_mensagens_recebidas()
    return render(request, 'base/indice_mensagens.html', {'mensagens': mensagens})


@login_required
@permission_required('base.view_contact', login_url='/nao_permitido/')
def detalhe_mensagem(request, id):
    mensagem = Contact.objects.get(id=id)
    return render(request, 'base/detalhe_mensagem.html', {'mensagem': mensagem})


@login_required
@permission_required('base.delete_contact', login_url='/nao_permitido/')
def remoc_contact(request, id):
    mensagem = Contact.objects.get(id=id)
    if request.method == 'POST':
        nome = mensagem.name
        path = request.path
        mensagem.delete()
        return render(request, 'base/remocao_concluida.html', {'nome': nome, 'path': path})
    return render(request, 'base/remoc_contact.html', {'mensagem': mensagem})

mcfields/base/templates/base/adic_subject.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/formularios.css' %}">
{% endblock css %}

{% block title %}
    {% if subject %}
        <title>McField's - Edição de Assunto</title>
    {% else %}
        <title>McField's - Novo Assunto</title>
    {% endif %}
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-adit-subject">
        {% if subject %}
            <h1 class="form-title">Edição do Assunto "{{ subject.title }}"</h1>
        {% else %}
            <h1 class="form-title">Novo Assunto</h1>
        {% endif %}
        <form class="disp-flex flex-dir-col" action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }} {{ field }}
                    <p class="errornote">{{ field.errors }}</p>
                </div>
                {{ field.help_text }}
            {% endfor %}
            <div class="form-buttons">
                <a class="canc-button" href="{% url 'base:subjects' %}">Cancelar</a>
                <button class="submit-button" type="submit">Publicar</button>
            </div>
        </form>
    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'base/js/adic_subject.js' %}" ></script>
{% endblock scripts %}

mcfields/base/templates/base/assuntos.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/assuntos.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Assuntos</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-subjects">
        <h1>Assuntos (Admin)</h1>
        {% if perms.base.add_subject %}
            <a id="subject-add-link" href="{% url 'base:adic_subject' %}">Novo Assunto</a>
        {% endif %}
        {% for sub in subjects %}
            <div class="subject-div">
                {% if perms.base.change_subject %}
                    <a class="subject-update-link" href="{{ sub.get_edition_url }}">Editar</a>
                {% endif %}
                {% if perms.base.delete_subject %}
                    <a class="subject-removal-link" href="{{ sub.get_removal_url }}">Remover</a>
                {% endif %}
                <div class="cover"></div>
                <h4>{{ sub.title }}</h4>
                <i class="bi bi-caret-down-fill light-green"></i>
            </div>
            <ol class="content-list hidden-videos">
                {% for video in sub.videos %}
                    <li class="list-item">
                        <a class="content-link" href="{{ video.get_absolute_url }}">
                            <i class="bi bi-film"></i>
                            {{ video.title }}
                        </a>
                    </li>
                {% endfor %}
                {% for news in sub.newsletters %}
                    <li class="list-item">
                        <a class="content-link" href="{{ news.get_absolute_url }}">
                            <i class="bi bi-envelope-paper"></i>
                            {{ news.title }}
                        </a>
                    </li>
                {% endfor %}
            </ol>
        {% endfor %}
    </div>
{% endblock maincontent_2 %}

{% block scripts %}
    <script src="{% static 'base/js/indice_assuntos.js' %}"></script>
{% endblock scripts %}

mcfields/base/templates/base/base_2.html
{% extends 'base/base.html' %}
{% load static %}

{% block css_base %}
    <link rel="stylesheet" href="{% static 'base/css/base_2.css' %}">
{% endblock css_base %}

{% block css %}
{% endblock css %}

{% block title %}
{% endblock title %}

{% block maincontent %}
    <div id="main-content-base2">
        {% block maincontent_2 %}
        {% endblock maincontent_2 %}
    </div>
{% endblock maincontent %}

mcfields/base/templates/base/contato.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/formularios.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/contato.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Contato</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-contact">
        <h1>Deixe-nos uma mensagem para entrarmos em contato</h1>
        <form id="contact-form" action="{% url 'base:contato' %}" method="POST">
            {% csrf_token %}
            <div class="form-field">
                {{ form.name.label_tag }} {{ form.name }}
                <p class="errornote">{{ form.name.errors }}</p>
                {{ form.name.help_text }}
            </div>
            <div class="form-field">
                {{ form.email.label_tag }} {{ form.email }}
                <p class="errornote">{{ form.email.errors }}</p>
                {{ form.email.help_text }}
            </div>
            <div class="form-field">
                {{ form.subject.label_tag }} {{ form.subject }}
                <p class="errornote">{{ form.subject.errors }}</p>
                {{ form.subject.help_text }}
            </div>
            <div class="form-field">
                {{ form.message.label_tag }} {{ form.message }}
                <p class="errornote">{{ form.message.errors }}</p>
                {{ form.message.help_text }}
            </div>
            <div id="priv-policy-div-form">
                <div id="aux-div">
                    {{ form.agree_with_policy }}
                    <label id="priv-policy-label" for="{{ form.agree_with_policy.id_for_label }}">
                        Estou ciente e de acordo com a <a href="{% url 'base:politica_privacidade' %}">Política de Privacidade</a>.
                    </label>
                </div>
                <p class="errornote">{{ form.agree_with_policy.errors }}</p>
                {{ form.agree_with_policy.help_text }}
            </div>
            <div class="form-buttons">
                <a class="canc-button" href="{% url 'base:home' %}">Cancelar</a>
                <button class="submit-button" type="submit">Enviar</button>
            </div>
        </form>
    </div>
{% endblock maincontent_2 %}

mcfields/base/templates/base/envio_msg_concludo.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block title %}
    <title>McField's - Mensagem enviada</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-message-sent">
        <h4 id="">Sua mensagem foi enviada com sucesso, retornaremos assim que possível. Obrigado!</h4>
    </div>
{% endblock maincontent_2 %}

mcfields/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>McField's - Home</title>
{% endblock title %}

{% block maincontent %}
    <div id="top-image-div" style="background-image: url({% static 'base/img/top_picture.jpg' %})">
        <div id="top-message">
            <h2>Bem vindo!</h2>
            <h4>Alguma mensagem de boas vindas para quem visita o site, ou o que achar interessante.</h4>
        </div>
    </div>

    <div id="about-consultant">
        <img id="about-consultant-img" src="{% static 'base/img/foto_victor_02.png' %}" alt="Foto do logotipo">
        <div id="about-text-div">
            <h1 id="about-consultant-title">Sobre o consultor</h1>
            <p id="about-consultant-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur distinctio dolorum ducimus eum,
                fuga harum id, incidunt iure mollitia nisi quas quidem, quisquam quos ratione sequi sint ullam veniam
                voluptatem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis consequuntur delectus
                impedit minima numquam quisquam reprehenderit tenetur? Accusamus aperiam assumenda ducimus, ex, ipsam
                iste magni neque non officia repellendus tempore!
            </p>
        </div>
    </div>

    <div id="our-services">
        <div id="our-services-div">
            <h1 id="our-services-title" >Serviços prestados</h1>
            <p id="our-services-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Aut blanditiis fuga fugit inventore modi ratione rerum
                sequi soluta unde veritatis? Dolorem dolores ipsam nulla,
                optio praesentium quaerat quod repellendus. Beatae.
                Lorem ipsum dolor sit amet, consectetur.
            </p>
        </div>

        <div id="slider">
            {% for servico in servicos %}
                <div class="slide">
                    <img src="{% get_media_prefix %}{{ servico.home_picture }}" alt="Foto relacionada ao serviço prestado">
                    <h3 class="slide-title">{{ servico.title }}</h3>
                    <p class="text-slide">{{ servico.intro }}</p>
                    <a id="know-more-button" href="{{ servico.get_absolute_url }}">Saiba mais</a>
                </div>
            {% empty %}
                <p>Não há serviços adicionados.</p>
                {% if perms.servicos.add_service %}
                    <a id="service-adit-link" href="{% url 'servicos:adicionar' %}">Adicione o primeiro</a>
                {% endif %}
            {% endfor %}
            <button class="btn btn-next"><i class="bi bi-chevron-compact-right"></i></button>
            <button class="btn btn-prev"><i class="bi bi-chevron-compact-left"></i></button>
        </div>
    </div>
    <div id="benefits">
        <h1 id="benefits-title">Benefícios</h1>
        <div id="benefits-list">
            <h3 class="benefits-list-title">Economia</h3>
            <p class="benefits-list-text">
                Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Impedit maxime non vel.
                Debitis dolorem dolores earum eius itaque
                magnam maiores nostrum numquam placeat
                porro, qui, sapiente similique totam ullam?
            </p>
            <h3 class="benefits-list-title">Maior produtividade</h3>
            <p class="benefits-list-text">
                Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Impedit maxime non vel.
                Debitis dolorem dolores earum eius itaque
                magnam maiores nostrum numquam placeat
                porro, qui, sapiente similique totam ullam?
            </p>
            <h3 class="benefits-list-title">Melhores resultados</h3>
            <p class="benefits-list-text">
                Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Impedit maxime non vel.
                Debitis dolorem dolores earum eius itaque
                magnam maiores nostrum numquam placeat
                porro, qui, sapiente similique totam ullam?
            </p>
        </div>
    </div>

    <div id="more-infos" style="background-image: url({% static 'base/img/background03.jpg' %})">
        <div id="more-infos-bg">
            <div id="more-infos-text">
                <h2>Ficou com alguma dúvida?</h2>
                <br>
                <h5>Entre em contato, será um prazer conhecê-lo para, juntos, buscarmos novas soluções.</h5>
            </div>
        </div>
    </div>
{% endblock maincontent %}

{% block scripts %}
    <script src="{% static 'base/js/home_page.js' %}" ></script>
{% endblock scripts %}

mcfields/base/templates/base/inscricao_concluida.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/inscricao_concluida.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Inscrição concluída</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-success-subscription">
        {% if email_errors or policy_agreement_errors %}
            <h4 class="main-msg">Seu email não pôde ser cadastrado pelos seguintes motivos:</h4>
            {% if policy_agreement_errors %}
                <h5>{{ policy_agreement_errors }}</h5>
            {% endif %}
            {% if email_errors %}
                <h5>{{ email_errors }}</h5>
            {% endif %}
        {% else %}
            <h4 class="main-msg">O email <strong>{{ email }}</strong> foi cadastrado com sucesso. Muito obrigado!</h4>
            <h5 class="main-msg-2">Fique atento à sua caixa de entrada de emails, você será notificado sempre que postarmos algum conteúdo.</h5>
        {% endif %}
    </div>
{% endblock maincontent_2 %}

mcfields/base/templates/base/msg_form_contato.html
<h3>
    Confira a nova mensagem de {{ name }} enviada através do website McField's Soluções Agrícolas.
    Para retornar, utilize o email informado: <a href="mailto:{{ email }}?subject={{ subject }}">{{ email }}</a>
</h3>
<br>
<p>{{ message|linebreaks }}</p>

mcfields/base/templates/base/nao_permitido.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/nao_permitido.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Acesso não permitido</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-content-not-allowed">
        <h4 id="not_allowed-msg">Desculpe, {{ user.first_name }}, mas você não tem acesso à este conteúdo.</h4>
    </div>
{% endblock maincontent_2 %}

mcfields/base/templates/base/remoc_contact.html
{% extends 'base/base_2.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'base/css/confirmacao_remocao.css' %}">
{% endblock css %}

{% block title %}
    <title>McField's - Confirmar remoção</title>
{% endblock title %}

{% block maincontent_2 %}
    <div id="main-cont-contact_removal">
        <h4 class="removal-msg">Tem certeza que deseja remover a mensagem de <strong>{{ mensagem.name }}</strong>?</h4>
        <form action="{% url 'base:remoc_contact' mensagem.id %}" method="POST">
            {% csrf_token %}
            <a class="canc-removal-button" href="{{ mensagem.get_absolute_url }}">Cancelar</a>
            <button class="conf-removal-button" type="submit">Confirmar</button>
        </form>
    </div>
{% endblock maincontent_2 %}